### ISSUE TITLE
Support useRouter and useRoute

### ISSUE THREAD

**Issue by vallemar** [MattCCC/nativescript-vue-router-extended#1]
That said, it would be amazing if it supports useRoute and useRouter from vue-router 4. By the way, great plugin

**Comment by MattCCC** [comment]
hi @vallemar, thanks for kind words! So ns-vue-next with composition api is currently experimental. It'll be quite tricky to bring a support for it, but I'll think about it and get back to you.

PRs are very welcomed as well 👍

**Comment by vallemar** [comment]
@MattCCC you are absolutely right!

**Comment by MattCCC** [comment]
@vallemar I've just released a new version that contains both useRouter and useRoute that will allow for router access within composition API. I hope it will make the plugin a bit more future-proof. It's experimental functionality so if you will face any issues, kindly please let me know in the thread.

**Comment by vallemar** [comment]
@MattCCC  Incredible! I will try it today! :100:

**Comment by deindesignpl** [comment]
Also, I spotted one thing if it comes to using reactivity of the hooks. I believe that when changing view w/o dismounting particular component current route _possibly_ wouldn't be updated.
