### ISSUE TITLE
Pass props not working

### ISSUE THREAD

**Issue by vallemar** [MattCCC/nativescript-vue-router-extended#2]
### Which platform(s) does your issue occur on?
- Test on android
- emulator

### Please, provide the following version numbers that your issue occurs with:
- 8.1.2

### Please, tell us how to recreate the issue in as much detail as possible. 
I am trying to pass props to a page and it is not working for me. I have tried it like this:
```js
methods:{
    toLogin(){
      this.$routeTo("/login" , { props: { successRedirect: '/home'}});
    }
  }
```
and so
```js
import {useRouter} from "nativescript-vue-router-extended";

setup(){
    const router = useRouter()
    const toLogin = () =>{
      router.push("/login" , { props: { successRedirect: '/home'}})
    }
    return { toLogin }
}
```
I have also set props to true in the routes just in case

```js
const routes = [
  {
    path: "/login",
    component: Login,
    props: true
  },
];
```

**Comment by MattCCC** [comment]
Hi, thanks for filing the issue. What does your `createRouter` function look like? Also does the redirection happen at all, just without props or not at all? Do you get any info when launching `ns debug android` in terminal?

**Comment by MattCCC** [comment]
I'm unable to reproduce this issue. In my setup props are passed correctly. Can you make a demo app with this issue reproduce? I will test it out then and push fix asap if needed.

**Comment by vallemar** [comment]
@MattCCC  I think it was my mistake, now I'm refactoring the code a lot and can't test it. I confirm when the refactor finishes. Thank you! and another thing, useRouter is sublime!

**Comment by MattCCC** [comment]
Sure, no worries. I gave it a few more tries but seems to be working just fine so far. Edit/ let me know once u test it pls, thanks 👍

**Comment by MattCCC** [comment]
Also, one more thing, may be a stupid question but do you register prop inside of your Login <Page />? Something like:

![image](https://user-images.githubusercontent.com/13603834/134777816-a5ebae0e-4569-4d91-a2a8-1c1fb19421d8.png)

**Comment by vallemar** [comment]
The problem was that I was in a tabbed view, and I had put the props on the first tab. She had not realized that the page was the father.  Sorry!!!!
